### ISSUE TITLE
xEAC not found after deployment stage 3

### ISSUE THREAD

**Issue by Califer** [ewg118/xEAC#9]
At the end of step 3 in the deployment guide (https://github.com/ewg118/xEAC/wiki) it says that the home page and admin page will be available, but I get a message saying "Orbeon Forms - Page Not Found" instead.  I removed the xeac part of the link and it showed Orbeon forms, so I believe that stages 1 and 2 were successfully installed.  I'm not sure what went wrong and I did step three twice just in case I made a typo but it still won't do anything for me.  

Does the symlink in step 4 need to have a name different from xeac?  I didn't see any place to tell it that the symlink I created was the one to use.

My site is located at 
http://xeac.staging.lib.utah.edu:8080/orbeon/xeac/

Thank you for any help you can give.

**Comment by ewg118** [comment]
Which version of Apache Tomcat are you using? This seems like a symlink problem, if you placed the symlink in $TOMCAT/webapps/orbeon/WEB-INF/resources/apps. I believe something has changed with activating symlinks between Tomcat 7 and 8.

**Comment by Califer** [comment]
Thank you for getting back to me!

I'm running Tomcat 7.  I have the symlink in /var/lib/tomcat7/webapps/orbeon/WEB-INF/resources/apps/.  The symlink is named 'xeac' (renamed from xEAC, as recommended) and is pointing the xeac folder that contains solr-home, xforms, ui, etc.

I have tested the symlink (just in case I screwed that up) by cd-ing into it from apps and it takes me into the xeac folder.

**Comment by ewg118** [comment]
Were you able to go to http://xeac.staging.lib.utah.edu:8080/orbeon/xeac/admin/ and create the xEAC config file and relevant exist-db project folders? xEAC is a little out of date compared to some changes I have made in other apps with regard to automatically redirecting to the admin panel if the config.xml file doesn't exist in the database yet.

**Comment by ewg118** [comment]
Actually, now that I have re-read the wiki, the cloning of the Github repository needs to come after deploying Solr and eXist-db to Tomcat, otherwise the config file can't be created. I have not transferred all of the documentation over from the old wiki (http://wiki.numismatics.org/xeac:xeac). While the old wiki is a little out of date, you still go to the admin panel after deploying all of the Tomcat applications in order to create your xEAC collection and project metadata, and the instructions for using the admin panel and the EAC-CPF editor are more or less the same.

**Comment by Califer** [comment]
I see you've updated the deployment guide.  I'll give it another go through tomorrow.  Thanks again!
